--- Tests for basilisk.log module.

describe("basilisk.log", function()
  local log = require("basilisk.log")

  describe("set_level", function()
    it("accepts valid log levels", function()
      assert.has_no.errors(function()
        log.set_level("trace")
      end)
      assert.has_no.errors(function()
        log.set_level("debug")
      end)
      assert.has_no.errors(function()
        log.set_level("info")
      end)
      assert.has_no.errors(function()
        log.set_level("warn")
      end)
      assert.has_no.errors(function()
        log.set_level("error")
      end)
    end)

    it("ignores invalid log levels", function()
      assert.has_no.errors(function()
        log.set_level("invalid")
      end)
    end)
  end)

  describe("logging functions", function()
    it("trace does not error", function()
      log.set_level("trace")
      assert.has_no.errors(function()
        log.trace("test message %s", "arg")
      end)
    end)

    it("debug does not error", function()
      log.set_level("debug")
      assert.has_no.errors(function()
        log.debug("test message %d", 42)
      end)
    end)

    it("info does not error", function()
      assert.has_no.errors(function()
        log.info("test message")
      end)
    end)

    it("warn does not error", function()
      assert.has_no.errors(function()
        log.warn("test warning")
      end)
    end)

    it("error does not error", function()
      assert.has_no.errors(function()
        log.error("test error")
      end)
    end)
  end)

  describe("file logging", function()
    it("enable_file does not error for valid path", function()
      local tmpfile = vim.fn.tempname() .. ".log"
      assert.has_no.errors(function()
        log.enable_file(tmpfile)
      end)
      log.info("file log test")
      log.close_file()

      -- Verify file was written.
      local fh = io.open(tmpfile, "r")
      if fh then
        local content = fh:read("*a")
        fh:close()
        assert.truthy(content:find("file log test"))
        os.remove(tmpfile)
      end
    end)

    it("close_file does not error when no file open", function()
      assert.has_no.errors(function()
        log.close_file()
      end)
    end)
  end)
end)
